# Generated by Django 5.1.5 on 2025-02-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_elrahmauser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elrahmauser',
            name='username',
        ),
        migrations.AlterField(
            model_name='elrahmauser',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
