# Generated by Django 5.1.5 on 2025-02-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='اخفاء'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المحافظة'),
        ),
        migrations.AlterField(
            model_name='address',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر التوصيل'),
        ),
    ]
