# Generated by Django 5.1.5 on 2025-02-19 23:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_address_hide_alter_address_name_and_more'),
        ('products', '0007_remove_product_image_4_alter_brand_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='عدد المنتج')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID الاوردر')),
                ('district', models.CharField(max_length=255, verbose_name='الحى')),
                ('apartment', models.CharField(max_length=255, verbose_name='الشقة')),
                ('street', models.CharField(max_length=255, verbose_name='الشارع')),
                ('building', models.CharField(max_length=255, verbose_name='المبنى')),
                ('floor', models.CharField(max_length=255, verbose_name='الدور')),
                ('raw_address', models.CharField(max_length=255, verbose_name='العنوان كامل كتابة')),
                ('is_cash_payment', models.BooleanField(default=False, verbose_name='الدفع كاش')),
                ('is_online_payment', models.BooleanField(default=True, verbose_name='الدفع اونلاين')),
                ('is_delivery_paid', models.BooleanField(default=False, verbose_name='تم دفع التوصيل')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوع')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.address', verbose_name='المحافظة')),
                ('items', models.ManyToManyField(to='orders.item', verbose_name='المنتجات')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'طلبات',
            },
        ),
    ]
