# Generated by Django 5.1.5 on 2025-02-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_price_alter_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take', models.BooleanField(default=False)),
                ('secret_key', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255)),
            ],
        ),
    ]
