# Generated by Django 5.1.5 on 2025-02-22 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_items_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='السعر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentaccountmodel',
            name='notification_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentaccountmodel',
            name='redirection_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PaymentMethodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('payment_method_id', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.paymentaccountmodel')),
            ],
        ),
    ]
