# Generated by Django 5.1.5 on 2025-02-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_item_amount_paymentaccountmodel_notification_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodmodel',
            name='payment_method_id',
            field=models.IntegerField(),
        ),
    ]
