# Generated by Django 5.1.5 on 2025-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_item_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='paymob_order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
