# Generated by Django 5.1.5 on 2025-02-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_links_paymob_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
