# Generated by Django 5.1.5 on 2025-02-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_links_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccountmodel',
            name='hmac_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
