# Generated by Django 5.1.5 on 2025-02-26 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_paymentaccountmodel_hmac_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.paymentmethodmodel'),
        ),
    ]
