# Generated by Django 5.1.5 on 2025-02-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
