# Generated by Django 5.1.5 on 2025-02-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_1_product_image_2_product_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
