# Generated by Django 5.1.5 on 2025-02-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_is_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'علامة تجارية', 'verbose_name_plural': 'العلامات التجارية'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'تصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
    ]
